KCalCam/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", include("main.urls")),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.index, name="index"),
]

main/models.py
from django.db import models

# Create your models here.
class Image(models.Model):
    userImage = models.ImageField()

main/views.py
from django.shortcuts import render, redirect
from .form import FormImage
from .models import Image
import logging
import yoloClassifier
import nutritionData
# Create your views here.

def index(request):
    img = Image.objects.all()

    if request.method == "POST":
        form = FormImage(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            obj=form.instance
            classified = yoloClassifier.main(obj.userImage.path, obj.userImage.path)
            foodInfo = nutritionData.getFoodInfo(classified[0][0])
            # print(foodInfo)
            return render(request, "main/choices.html", {"food":foodInfo, "obj":obj})
    else:
        form = FormImage()

    return render(request, "main/index.html", {"img": img, "form":form})

main/templates/main/choices.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>KCalCam | Calorie Tracker</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"/>
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    
        <style>
            body {
                background-color: black;
                color:black;
            }
        </style>

        <script>
              $(document).ready(function(){
                    $('.modal').modal();
                });
        </script>
    </head>

    <body>
        <div class="container">
            <div class="row center height valign-wrapper">
                <div class="col s12">
                    <img class="responsive-img" src="{{obj.userImage.url}}" alt="imagePog">
                    <h3 style="color:white;">Select The Best Fit</h3>

                    <div class="collection">
                        {% for ids in food %}
                        <a href="#{{ids}}" class="collection-item modal-trigger">{{ids}}</a>
                        {% endfor %}
                    </div>

                    {% for id, info in food.items %}
                        <div id="{{id}}" class="modal">
                            <div class="modal-content">
                                {% for i in info %}
                                    <h6>{{i}}</h6>
                                {% endfor %}
                            </div>

                            <div class="modal-footer">
                                <a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a>
                            </div>
                        </div>
                    {% endfor %}

                </div>
            </div>
        </div>
    </body>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
</html>

main/templates/main/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>KCalCam | Calorie Tracker</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"/>
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    
        <style>
            body {
                background-color: black;
            }

            .height {
                margin: 0px;
                padding:0px;
                float: left;
                width: 90%;
                position:absolute;
                top: 50%;
                transform: translateY(-50%) translateX(-50%);
                left:50%;
            }

            input[type="file"] {
                display:none;
            }
        </style>
    </head>

    <body>
        <div class="container">
            <div class="row center height valign-wrapper">
                <div class="col s12">
                    <form action="." method="post", enctype="multipart/form-data">
                        {% csrf_token %}
                        <!-- {{form.as_table}} -->
                        {%for field in form%}
                            <input type="file" id="file" name="userImage" accept="image/*" required id="id_userImage" >
                            <label for="file" class="waves-effect waves-light btn-large light-blue accent-4 hover">
                                <i class="material-icons left">add_a_photo</i>
                                Add Picture
                            </label>
                        {%endfor%}

                        <button type="submit" class="waves-effect waves-light btn-large light-blue accent-4 hover"><i class="material-icons left">file_upload</i>Uplaod PPicture To Scan</button>
                    </form>
                </div>
            </div>
        </div>
    </body>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
</html>